# -*- coding: utf-8 -*-
"""
Root cause: IKR_SwordToCharacters had empty chain mappings → legs not retargeted.
Fix: AutoMapChains + re-retarget SwordRTG + disable Foot IK on ABP.
"""

from __future__ import annotations

import unreal

OUT = "/Game/Characters/\u6797\u7b26/\u52a8\u753b"
RTG_DIR = f"{OUT}/SwordRTG"
IKR = f"{OUT}/IK/IKR_SwordToCharacters"
IK_CHAR = f"{OUT}/IK/IK_Characters_Manny"
CHA2 = "/Game/Sword_Animations/Demo/Mannequins/Character/Meshes/Cha_2_IKRig"
SRC_MESH = "/Game/Sword_Animations/Demo/Mannequins/Character/Meshes/SKM_Manny"
TGT_MESH = "/Game/Characters/Mannequins/Meshes/SKM_Manny_Simple"
ABP = f"{OUT}/ABP_StrafeLocomotion"
BS = "/Game/Characters/Mannequins/Anims/Unarmed/BS_WalkRun_Sword"

SRC_ANIMS = [
    "/Game/Sword_Animations/Animations/Sequence2/01_Idle/Idle_Seq",
    # Walk loops
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/01_Walk_F_0/Walk_Loop_F_0_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/02_Walk_F_L_45/Walk_Loop_F_L_45_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/03_Walk_F_R_45/Walk_Loop_F_R_45_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/04_Walk_F_L_90/Walk_Loop_F_L_90_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/05_Walk_F_R_90/Walk_Loop_F_R_90_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/06_Walk_B_180/Walk_Loop_B_180_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/07_Walk_B_L_45/Walk_Loop_B_L_45_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/08_Walk_B_R_45/Walk_Loop_B_R_45_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/09_Walk_B_L_90/Walk_Loop_B_L_90_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/03_Walk/01_Walk/10_Walk_B_R_90/Walk_Loop_B_R_90_Seq",
    # Run loops
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/01_Run_F_0/Run_Loop_F_0_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/02_Run_F_L_45/Run_Loop_F_L_45_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/03_Run_F_R_45/Run_Loop_F_R_45_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/04_Run_F_L_90/Run_Loop_F_L_90_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/05_Run_F_R_90/Run_Loop_F_R_90_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/06_Run_B_180/Run_Loop_B_180_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/07_Run_B_L_45/Run_Loop_B_L_45_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/08_Run_B_R_45/Run_Loop_B_R_45_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/09_Run_B_L_90/Run_Loop_B_L_90_Seq",
    "/Game/Sword_Animations/Animations/Sequence2/04_Run/01_Run/10_Run_B_R_90/Run_Loop_B_R_90_Seq",
]


def log(m):
    unreal.log(f"[FixLegs2] {m}")


def load(p):
    a = unreal.EditorAssetLibrary.load_asset(p)
    if not a:
        raise RuntimeError(f"missing {p}")
    return a


def save(p):
    unreal.EditorAssetLibrary.save_asset(p, only_if_is_dirty=False)


def chain_names(ik_path: str):
    ik = load(ik_path)
    ctrl = unreal.IKRigController.get_controller(ik)
    names = []
    for ch in ctrl.get_retarget_chains() or []:
        try:
            names.append(str(ch.get_editor_property("chain_name")))
        except Exception:
            names.append(str(ch))
    root = None
    try:
        root = ctrl.get_retarget_root()
    except Exception:
        pass
    log(f"{ik_path.split('/')[-1]} root={root} chains={names}")
    return names


def remap_ikr():
    src_ik = load(CHA2)
    char_ik = load(IK_CHAR)
    src_mesh = load(SRC_MESH)
    tgt_mesh = load(TGT_MESH)
    ikr = load(IKR)

    # Refresh target IK def
    cctrl = unreal.IKRigController.get_controller(char_ik)
    cctrl.set_skeletal_mesh(tgt_mesh)
    try:
        cctrl.apply_auto_generated_retarget_definition()
        log("target ApplyAutoGeneratedRetargetDefinition")
    except Exception as exc:
        log(f"auto def: {exc}")
    try:
        cctrl.apply_auto_fbik()
        log("target ApplyAutoFBIK")
    except Exception as exc:
        log(f"auto fbik: {exc}")
    save(IK_CHAR)

    src_names = set(chain_names(CHA2))
    tgt_names = set(chain_names(IK_CHAR))
    common = sorted(src_names & tgt_names)
    log(f"common chains ({len(common)}): {common}")

    rctrl = unreal.IKRetargeterController.get_controller(ikr)
    rctrl.set_ik_rig(unreal.RetargetSourceOrTarget.SOURCE, src_ik)
    rctrl.set_ik_rig(unreal.RetargetSourceOrTarget.TARGET, char_ik)
    rctrl.set_preview_mesh(unreal.RetargetSourceOrTarget.SOURCE, src_mesh)
    rctrl.set_preview_mesh(unreal.RetargetSourceOrTarget.TARGET, tgt_mesh)
    try:
        rctrl.add_default_ops()
        log("AddDefaultOps")
    except Exception as exc:
        log(f"AddDefaultOps: {exc}")

    # Clear then Exact + Fuzzy
    mapped = False
    for tname in ("CLEAR", "Clear", "EXACT", "Exact", "FUZZY", "Fuzzy"):
        if not hasattr(unreal.AutoMapChainType, tname):
            continue
        try:
            rctrl.auto_map_chains(getattr(unreal.AutoMapChainType, tname), True)
            log(f"AutoMapChains {tname} ok")
            if tname.lower() != "clear":
                mapped = True
        except Exception as exc:
            log(f"AutoMapChains {tname}: {exc}")

    # Manual SetSourceChain for important limbs
    important = [
        "Spine",
        "Neck",
        "Head",
        "LeftLeg",
        "RightLeg",
        "LeftFoot",
        "RightFoot",
        "LeftArm",
        "RightArm",
        "LeftClavicle",
        "RightClavicle",
    ]
    for name in important:
        if name in src_names and name in tgt_names:
            try:
                ok = rctrl.set_source_chain(unreal.Name(name), unreal.Name(name))
                log(f"SetSourceChain {name}->{name}: {ok}")
            except Exception:
                try:
                    ok = rctrl.set_source_chain(name, name)
                    log(f"SetSourceChain str {name}: {ok}")
                except Exception as exc:
                    log(f"SetSourceChain {name}: {exc}")

    settings = []
    try:
        settings = list(rctrl.get_all_chain_settings() or [])
    except Exception as exc:
        log(f"get_all_chain_settings: {exc}")
    log(f"chain_settings count={len(settings)}")
    for s in settings[:30]:
        bits = []
        for prop in (
            "source_chain",
            "target_chain",
            "SourceChain",
            "TargetChain",
            "enabled",
        ):
            try:
                bits.append(f"{prop}={s.get_editor_property(prop)}")
            except Exception:
                pass
        # URetargetChainSettings often has TargetChainName
        for prop in ("target_chain_name", "TargetChainName", "source_chain_name", "SourceChainName"):
            try:
                bits.append(f"{prop}={s.get_editor_property(prop)}")
            except Exception:
                pass
        try:
            bits.append(f"name={s.get_name()}")
        except Exception:
            pass
        log(f"  setting {bits}")

    if len(settings) == 0:
        log("WARNING: still no chain settings — retarget will stay broken")
    save(IKR)
    return ikr, len(settings)


def reretarget(ikr):
    src_mesh = load(SRC_MESH)
    tgt_mesh = load(TGT_MESH)
    datas = []
    for p in SRC_ANIMS:
        # Try alternate folder numbers if missing
        if unreal.EditorAssetLibrary.does_asset_exist(p):
            datas.append(unreal.EditorAssetLibrary.find_asset_data(p))
        else:
            log(f"missing src {p}")

    # Also discover any existing walk/run loop under Sequence2 if list incomplete
    log(f"retargeting {len(datas)} assets")
    inputs = unreal.IKRetargetBatchOperationInputs()
    inputs.set_editor_property("assets_to_retarget", datas)
    inputs.set_editor_property("source_mesh", src_mesh)
    inputs.set_editor_property("target_mesh", tgt_mesh)
    inputs.set_editor_property("ik_retarget_asset", ikr)
    inputs.set_editor_property("search", "")
    inputs.set_editor_property("replace", "")
    inputs.set_editor_property("prefix", "")
    inputs.set_editor_property("suffix", "_RTG")
    inputs.set_editor_property("target_path", RTG_DIR)
    inputs.set_editor_property("use_source_path", False)
    inputs.set_editor_property("include_referenced_assets", False)
    inputs.set_editor_property("overwrite_existing_files", True)

    created = unreal.IKRetargetBatchOperation.run_batch_retarget(inputs) or []
    log(f"created={len(created)}")
    try:
        unreal.EditorAssetLibrary.save_directory(RTG_DIR, only_if_is_dirty=False, recursive=True)
    except Exception as exc:
        log(f"save dir: {exc}")
        for ad in created:
            try:
                obj = ad.get_asset()
                path = obj.get_path_name().split(".")[0]
                save(path)
            except Exception:
                pass
    return len(created)


def disable_foot_ik():
    abp = load(ABP)
    cls = getattr(unreal, "AnimGraphNode_ControlRig", None)
    n = 0
    if cls:
        for obj in unreal.ObjectIterator(cls):
            try:
                if "ABP_StrafeLocomotion" not in obj.get_path_name():
                    continue
            except Exception:
                continue
            for outer in ("node", "Node"):
                try:
                    node = obj.get_editor_property(outer)
                except Exception:
                    continue
                if not node:
                    continue
                try:
                    node.set_editor_property("alpha", 0.0)
                    obj.set_editor_property(outer, node)
                    n += 1
                    log("FootIK alpha=0")
                except Exception as exc:
                    log(f"alpha: {exc}")
    try:
        unreal.BlueprintEditorLibrary.compile_blueprint(abp)
    except Exception as exc:
        log(f"compile: {exc}")
    save(ABP)
    log(f"footik disabled tweaks={n}")


def touch_bs():
    """Force BS to reload sample anims after overwrite."""
    if not unreal.EditorAssetLibrary.does_asset_exist(BS):
        return
    bs = load(BS)
    samples = bs.get_editor_property("sample_data")
    log(f"BS samples={len(samples) if samples else 0}")
    # re-assign animation refs to force update
    if samples:
        for s in samples:
            try:
                anim = s.get_editor_property("animation")
                if anim:
                    s.set_editor_property("animation", anim)
            except Exception:
                pass
        try:
            bs.set_editor_property("sample_data", samples)
        except Exception:
            pass
    save(BS)


def run():
    log("start")
    ikr, nset = remap_ikr()
    if nset == 0:
        # One more try: Exact only with force
        rctrl = unreal.IKRetargeterController.get_controller(ikr)
        try:
            rctrl.auto_map_chains(unreal.AutoMapChainType.FUZZY, True)
            nset = len(list(rctrl.get_all_chain_settings() or []))
            log(f"retry fuzzy settings={nset}")
            save(IKR)
        except Exception as exc:
            log(f"retry: {exc}")

    created = reretarget(ikr)
    disable_foot_ik()
    touch_bs()
    log(f"done chain_settings={nset} retargeted={created}")


if __name__ == "__main__":
    run()
else:
    run()
