# -*- coding: utf-8 -*-
import unreal

ABP = "/Game/Characters/\u6797\u7b26/\u52a8\u753b/ABP_StrafeLocomotion"


def log(m):
    unreal.log(f"[ProbeGE] {m}")


bp = unreal.EditorAssetLibrary.load_asset(ABP)

for tr_name in ("AnimStateTransitionNode_16", "AnimStateTransitionNode_18", "AnimStateTransitionNode_0", "AnimStateTransitionNode_2"):
    tr = None
    for n in unreal.ObjectIterator(unreal.AnimStateTransitionNode):
        if n.get_name() == tr_name and "ABP_StrafeLocomotion" in n.get_path_name():
            tr = n
            break
    if not tr:
        log(f"missing {tr_name}")
        continue
    for g in unreal.ObjectIterator(unreal.EdGraph):
        if g.get_outer() != tr:
            continue
        for n in unreal.ObjectIterator(unreal.EdGraphNode):
            if n.get_outer() != g:
                continue
            title = str(n.get_node_title()) if hasattr(n, "get_node_title") else n.get_class().get_name()
            if "float" not in title and "GroundSpeed" not in title:
                continue
            log(f"{tr_name} node={title}")
            try:
                for p in n.list_all_pins():
                    info = {}
                    for meth in (
                        "get_pin_name",
                        "get_default_as_string",
                        "get_autogenerated_default_value",
                        "has_any_connections",
                        "is_connected",
                    ):
                        if hasattr(p, meth):
                            try:
                                v = getattr(p, meth)
                                info[meth] = v() if callable(v) else v
                            except Exception as e:
                                info[meth] = f"err:{e}"
                    # linked
                    try:
                        linked = p.get_linked_to()
                        info["linked"] = [str(x.get_owning_node().get_node_title()) for x in linked]
                    except Exception as e:
                        info["linked"] = str(e)
                    log(f"  pin {info}")
            except Exception as e:
                log(f"  list pins err {e}")

log("done")
