# -*- coding: utf-8 -*-
"""Dump float literals + priority on turn-related transitions."""
import unreal

ABP = "/Game/Characters/\u6797\u7b26/\u52a8\u753b/ABP_StrafeLocomotion"


def log(m):
    unreal.log(f"[ProbeLit] {m}")


def under_abp(n, bp):
    o = n
    for _ in range(16):
        if o == bp:
            return True
        try:
            o = o.get_outer()
        except Exception:
            return False
        if o is None:
            return False
    return False


bp = unreal.EditorAssetLibrary.load_asset(ABP)

for tr in unreal.ObjectIterator(unreal.AnimStateTransitionNode):
    if not under_abp(tr, bp):
        continue
    try:
        if tr.get_outer().get_name() != "Locomotion":
            continue
    except Exception:
        continue

    # only turn-related
    titles = []
    for g in unreal.ObjectIterator(unreal.EdGraph):
        if g.get_outer() != tr:
            continue
        for n in unreal.ObjectIterator(unreal.EdGraphNode):
            if n.get_outer() != g:
                continue
            try:
                titles.append(str(n.get_node_title()))
            except Exception:
                pass
    joined = " | ".join(titles)
    if "Turn" not in joined and "GroundSpeed" not in joined:
        continue

    prio = cross = auto = None
    for prop in ("priority_order", "PriorityOrder", "transition_priority_order"):
        try:
            prio = tr.get_editor_property(prop)
            break
        except Exception:
            pass
    try:
        auto = tr.get_editor_property("automatic_rule_based_on_sequence_player_in_state")
    except Exception:
        pass
    try:
        cross = tr.get_editor_property("crossfade_duration")
    except Exception:
        pass

    log(f"=== {tr.get_name()} auto={auto} prio={prio} cross={cross} ===")
    for g in unreal.ObjectIterator(unreal.EdGraph):
        if g.get_outer() != tr:
            continue
        for n in unreal.ObjectIterator(unreal.EdGraphNode):
            if n.get_outer() != g:
                continue
            cname = n.get_class().get_name()
            title = ""
            try:
                title = str(n.get_node_title())
            except Exception:
                title = cname
            # dump numeric defaults on pins / properties
            extras = []
            for attr in ("default_value", "DefaultValue", "value", "Value"):
                if hasattr(n, attr):
                    try:
                        extras.append(f"{attr}={getattr(n, attr)}")
                    except Exception:
                        pass
            # pins via find_* if K2
            try:
                for p in n.list_all_pins():
                    try:
                        pname = str(p.get_pin_name())
                    except Exception:
                        pname = "?"
                    dv = None
                    for meth in ("get_default_as_string", "default_value", "DefaultValue"):
                        try:
                            if hasattr(p, meth):
                                dv = getattr(p, meth)
                                if callable(dv):
                                    dv = dv()
                                break
                        except Exception:
                            pass
                    # also try editor property
                    if dv is None:
                        for prop in ("default_value", "DefaultValue", "autogenerated_default_value"):
                            try:
                                dv = p.get_editor_property(prop)
                                break
                            except Exception:
                                pass
                    if dv not in (None, "", "0", "0.0") or pname in ("B", "A", "Value"):
                        extras.append(f"pin:{pname}={dv}")
            except Exception as e:
                extras.append(f"pinerr={e}")

            log(f"  {cname}: {title} | {extras}")

log("done")
