# -*- coding: utf-8 -*-
"""只读导出战斗、命中判定与处决相关蓝图和动画信息。"""

from pathlib import Path
import unreal


ASSETS = [
    "/Game/蓝图/玩家/BPC_攻击系统",
    "/Game/蓝图/玩家/BP_ThirdPersonCharacter",
    "/Game/蓝图/玩家/BP_动画状态剑追踪",
    "/Game/蓝图/BPC_敌人状态",
    "/Game/蓝图/BP_测试假人",
    "/Game/蓝图/BPI_暗杀",
]
EXECUTION_ASSETS = [
    "/Game/Characters/林符/动画/Montages/处决/处决1",
    "/Game/Characters/林符/动画/Montages/处决/处决2",
    "/Game/Characters/林符/动画/Montages/处决/处决3",
    "/Game/Characters/人形怪/被处决动画/被处决1",
    "/Game/Characters/人形怪/被处决动画/被处决2",
    "/Game/Characters/人形怪/被处决动画/被处决3",
    "/Game/Sword_Animations/Animations/Sequence1/02_Attack/15_Execution/01_Execution/Execution_01_Seq",
    "/Game/Sword_Animations/Animations/Sequence1/02_Attack/15_Execution/01_Execution/Execution_02_Seq",
    "/Game/Sword_Animations/Animations/Sequence1/02_Attack/15_Execution/01_Execution/Execution_03_Seq",
    "/Game/Sword_Animations/Animations/Sequence1/02_Attack/15_Execution/02_Target/Execution_Target_01_Seq",
    "/Game/Sword_Animations/Animations/Sequence1/02_Attack/15_Execution/02_Target/Execution_Target_02_Seq",
    "/Game/Sword_Animations/Animations/Sequence1/02_Attack/15_Execution/02_Target/Execution_Target_03_Seq",
]
REPORT = Path(__file__).with_name("inspect_combat_system_report.txt")
LINES = []
BEL = unreal.BlueprintEditorLibrary


def log(message):
    text = str(message)
    LINES.append(text)
    unreal.log(f"[CombatInspect] {text}")


def prop(obj, name, fallback="<n/a>"):
    try:
        return obj.get_editor_property(name)
    except Exception:
        return fallback


def pin_text(pin):
    name = str(pin.get_pin_name())
    default = ""
    for method_name in ("get_default_value", "get_autogenerated_default_value"):
        try:
            default = str(getattr(pin, method_name)())
            break
        except Exception:
            pass
    if not default:
        default = str(prop(pin, "default_value", ""))
    try:
        links = [
            f"{item.get_owning_node().get_name()}.{item.get_pin_name()}"
            for item in (pin.list_connected_pins() or [])
        ]
    except Exception:
        links = []
    return f"{name}={default!r}->{links}"


def inspect_blueprint(path):
    asset = unreal.EditorAssetLibrary.load_asset(path)
    if not asset:
        log(f"MISSING {path}")
        return

    log(f"\n=== BLUEPRINT {path} class={asset.get_class().get_name()} ===")
    log(f"parent_class={prop(asset, 'parent_class')}")
    log(f"implemented_interfaces={prop(asset, 'implemented_interfaces')}")

    variables = list(prop(asset, "new_variables", []) or [])
    log(f"variables={len(variables)}")
    cdo = None
    try:
        cdo = unreal.get_default_object(asset.generated_class())
    except Exception as exc:
        log(f"CDO error={exc}")
    for variable in variables:
        name = str(prop(variable, "var_name", "<unknown>"))
        default_value = prop(variable, "default_value", "")
        current = "<n/a>"
        if cdo:
            current = prop(cdo, name)
        log(f" VAR {name} default={default_value!r} current={current}")

    if cdo:
        try:
            components = list(cdo.get_components_by_class(unreal.ActorComponent) or [])
        except Exception:
            components = []
        for component in components:
            details = []
            for key in (
                "relative_location",
                "relative_rotation",
                "relative_scale3d",
                "collision_enabled",
                "collision_profile_name",
                "generate_overlap_events",
                "sphere_radius",
                "capsule_radius",
                "capsule_half_height",
            ):
                value = prop(component, key)
                if value != "<n/a>":
                    details.append(f"{key}={value}")
            log(f" COMPONENT {component.get_name()} {component.get_class().get_name()} {' '.join(details)}")

    graphs = []
    for graph in unreal.ObjectIterator(unreal.EdGraph):
        try:
            if asset.get_name() in graph.get_path_name():
                graphs.append(graph)
        except Exception:
            pass
    seen = set()
    for graph in sorted(graphs, key=lambda item: item.get_path_name()):
        if graph.get_path_name() in seen:
            continue
        seen.add(graph.get_path_name())
        log(f" GRAPH {graph.get_path_name()}")
        nodes = []
        for node in unreal.ObjectIterator(unreal.EdGraphNode):
            try:
                if node.get_outer() == graph:
                    nodes.append(node)
            except Exception:
                pass
        nodes.sort(key=lambda item: (int(prop(item, "node_pos_y", 0)), int(prop(item, "node_pos_x", 0))))
        for node in nodes:
            try:
                title = str(BEL.get_node_title(node))
            except Exception:
                title = node.get_name()
            pins = []
            try:
                pins = [pin_text(item) for item in (BEL.list_all_pins(node) or [])]
            except Exception:
                pass
            log(
                f"  NODE {node.get_name()} {node.get_class().get_name()} "
                f"pos=({prop(node, 'node_pos_x', 0)},{prop(node, 'node_pos_y', 0)}) "
                f"title={title!r} pins={pins}"
            )


def inspect_animation(path):
    asset = unreal.EditorAssetLibrary.load_asset(path)
    if not asset:
        log(f"MISSING {path}")
        return
    log(f"\n=== ANIMATION {path} class={asset.get_class().get_name()} ===")
    for key in (
        "sequence_length",
        "rate_scale",
        "enable_root_motion",
        "root_motion_root_lock",
        "force_root_lock",
        "root_motion_mode",
        "retarget_source",
        "retarget_source_asset_reference_pose",
        "blend_in",
        "blend_out",
        "blend_out_trigger_time",
        "sync_group",
        "slot_anim_tracks",
        "notifies",
        "composite_sections",
    ):
        value = prop(asset, key)
        if value != "<n/a>":
            try:
                value = value.export_text()
            except Exception:
                pass
            log(f" {key}={value}")

    registry = unreal.AssetRegistryHelpers.get_asset_registry()
    try:
        dependencies = registry.get_dependencies(
            unreal.Name(path),
            unreal.AssetRegistryDependencyOptions(True, True, True, True),
        )
    except Exception:
        dependencies = []
    log(f" dependencies={[str(item) for item in dependencies]}")


def main():
    for path in ASSETS:
        inspect_blueprint(path)
    for path in EXECUTION_ASSETS:
        inspect_animation(path)
    REPORT.write_text("\n".join(LINES), encoding="utf-8")


main()
